language: c
sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
env:
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
  
before_script:
  - ./test/setup.sh

script:
  - make -C test -f test.make normal.test
  - make -C test -f test.make gc64.test
  - make -C test -f test.make dualnum.test
  - make -C test -f test.make nojit.test

